export function ChampionsMegaOnlyAbilities() {
    return championsMegaOnlyAbilities;
}

// Abilities that only apply to the Mega form in Pokémon Champions.
// Base-form species cannot be submitted with these abilities on RK9.
const championsMegaOnlyAbilities = {
    "Venusaur": ["Thick Fat"],
    "Charizard": ["Tough Claws", "Drought"],
    "Blastoise": ["Mega Launcher"],
    "Beedrill": ["Adaptability"],
    "Pidgeot": ["No Guard"],
    "Clefable": ["Magic Bounce"],
    "Victreebel": ["Innards Out"],
    "Slowbro": ["Shell Armor"],
    "Gengar": ["Shadow Tag"],
    "Kangaskhan": ["Parental Bond"],
    "Starmie": ["Huge Power"],
    "Pinsir": ["Aerilate"],
    "Gyarados": ["Mold Breaker"],
    "Aerodactyl": ["Tough Claws"],
    "Meganium": ["Mega Sol"],
    "Feraligatr": ["Dragonize"],
    "Ampharos": ["Mold Breaker"],
    "Steelix": ["Sand Force"],
    "Heracross": ["Skill Link"],
    "Skarmory": ["Stalwart"],
    "Houndoom": ["Solar Power"],
    "Gardevoir": ["Pixilate"],
    "Sableye": ["Magic Bounce"],
    "Aggron": ["Filter"],
    "Manectric": ["Intimidate"],
    "Sharpedo": ["Strong Jaw"],
    "Camerupt": ["Sheer Force"],
    "Altaria": ["Pixilate"],
    "Banette": ["Prankster"],
    "Absol": ["Magic Bounce"],
    "Glalie": ["Refrigerate"],
    "Lopunny": ["Scrappy"],
    "Garchomp": ["Sand Force"],
    "Lucario": ["Adaptability"],
    "Gallade": ["Inner Focus"],
    "Froslass": ["Snow Warning"],
    "Emboar": ["Mold Breaker"],
    "Excadrill": ["Piercing Drill"],
    "Chesnaught": ["Bulletproof"],
    "Delphox": ["Levitate"],
    "Greninja": ["Protean"],
    "Floette": ["Fairy Aura"],
    "Meowstic": ["Trace"],
    "Meowstic-F": ["Trace"],
    "Hawlucha": ["No Guard"],
    "Scovillain": ["Spicy Spray"],
    "Glimmora": ["Adaptability"],
    "Golurk": ["Unseen Fist"]
};
